mysql:
  username: root
  password: admin
  dbname: cyzb
  ip: 127.0.0.1
  port: 3306
messages:
  start-verify-kick: "§f§lCy§b§lVerify\n§e请使用§c正版账号§e的方式登录§6zb.cyttt.cn§e完成验证！/n§7/n§7如果出现<远程主机关闭现有的连接>或其他非正常断开情况/n§7不用担心,不用重新进入,直接返回主服领取奖励!"
  verfiy-success: "§f§lCy§b§lVerify\n§2✔ §a正版验证成功 感谢你对正版的支持"
  not-exist: "§f§lCy§b§lVerify\n§c请先在主服务器输入/cy start 开始验证！"
  already-verified: "§f§lCy§b§lVerify\n§c你已经验证过了"
  verfiy-title: "§f§lCy§b§lVerify\n§6验证成功,你现在可以返回主服务器了！"
  verified: "§f§lCy§b§lVerify §8» §c你已经验证过了,有问题请联系管理员解决!"
command_success: "lp user %player% parent add zbuser"
