main: airio.cyverify.main
name: CyVerify
version: 1.1
description: a simple zb verify plugin
commands:
  cy:
    aliases:
      - zb
      - love
    permission: cy.verify
permissions:
  cy.verify:
    default: true
    description: noob
  cy.all:
    default: op
    description: all

